# Template for Formula/drivethru.rb in https://github.com/ja-godfrey/homebrew-tap
# See packaging/README.md for the release steps (tag, sha256, audit, test).
class Drivethru < Formula
  desc "Fuzzy-find Google Drive for desktop files and copy their share links"
  homepage "https://github.com/ja-godfrey/drivethru"
  url "https://github.com/ja-godfrey/drivethru/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "REPLACE_WITH_SHA256"
  license "MIT"
  head "https://github.com/ja-godfrey/drivethru.git", branch: "main"

  depends_on macos: :ventura
  depends_on "fzf"

  def install
    bin.install "drivethru"
    pkgshare.install Dir["share/drivethru/*"]
  end

  def caveats
    <<~EOS
      drivethru reads the folders that Google Drive for desktop keeps in
      ~/Library/CloudStorage. If you don't have it yet:
        brew install --cask google-drive

      To add the Finder Quick Action:
        drivethru install-quick-action

      To check your setup:
        drivethru doctor
    EOS
  end

  test do
    # brew test runs with HOME=testpath, so this fake mount is the only
    # Google Drive account drivethru can see. The paths contain spaces, so
    # every path passed through shell_output is shell-escaped.
    xattr = "com.google.drivefs.item-id#S"
    doc_id = "1FakeDocIdForTheHomebrewTestOnly0000000000A"
    folder_id = "1FakeFolderIdForTheBrewTest000000"

    mount = testpath/"Library/CloudStorage/GoogleDrive-test@example.com"
    my_drive = mount/"My Drive"
    folder = my_drive/"Team Notes"
    folder.mkpath
    system "/usr/bin/xattr", "-w", xattr, "0AFakeMyDriveRootUk9PVA", my_drive
    system "/usr/bin/xattr", "-w", xattr, folder_id, folder

    doc = folder/"Project Plan.gdoc"
    doc.write <<~JSON
      {"":"WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!","doc_id":"#{doc_id}","resource_key":"","email":"test@example.com"}
    JSON
    system "/usr/bin/xattr", "-w", xattr, doc_id, doc

    assert_equal "https://docs.google.com/document/d/#{doc_id}/edit",
                 shell_output("#{bin}/drivethru link #{doc.to_s.shellescape}").strip
    assert_equal "https://drive.google.com/drive/folders/#{folder_id}",
                 shell_output("#{bin}/drivethru link #{folder.to_s.shellescape}").strip

    # A file that hasn't uploaded yet has no item id: exit status 3.
    local_only = folder/"Not uploaded yet.txt"
    local_only.write "local only\n"
    shell_output("#{bin}/drivethru link #{local_only.to_s.shellescape}", 3)

    # The script carries its own version string; check it matches the tag.
    assert_match version.to_s, shell_output("#{bin}/drivethru --version") if stable?
  end
end
